import assert from "node:assert/strict";
import test from "node:test";
import { loadTypeScript } from "./helpers/load-typescript.mjs";

const { parseLatestRelease } = loadTypeScript("src/lib/changelog.ts");

test("reads the newest release generated by release-it", () => {
  const notes = parseLatestRelease(`# Changelog

## [1.1.0](https://github.com/Marcus-Boni/Auto-Daily-App/compare/v1.0.0...v1.1.0) (2026-10-10)

### Novas funcionalidades

* **daily:** adiciona formato semanal ([abc1234](https://github.com/Marcus-Boni/Auto-Daily-App/commit/abc1234))

## [1.0.0] - 2026-10-04

### Novas Funcionalidades
- Primeira versão.
`);
  assert.equal(notes.version, "1.1.0");
  assert.equal(notes.date, "2026-10-10");
  assert.match(notes.body, /formato semanal/);
  assert.doesNotMatch(notes.body, /Primeira versão/);
});

test("reads hand-written headings, first releases and trailing separators", () => {
  const manual = parseLatestRelease(
    "# Changelog\n\n## [1.0.0] - 2026-10-04\n\n- Primeira versão.\n\n---\n"
  );
  assert.deepEqual(manual, { version: "1.0.0", date: "2026-10-04", body: "- Primeira versão." });

  const first = parseLatestRelease(
    "# Changelog\n\n## 1.0.1 (2026-10-12)\n\n### Correções\n\n* corrige cópia\n"
  );
  assert.equal(first.version, "1.0.1");
  assert.equal(first.date, "2026-10-12");
});

test("returns null when the changelog has no release yet", () => {
  assert.equal(parseLatestRelease("# Changelog\n\nNada publicado ainda.\n"), null);
});
